name: "ParallelCTF"
version: "1.5"
main: parallelmc.ctf.ParallelCTF
api-version: 1.18
author: EBro912
description: A Capture the Flag plugin for Parallel events
depend: [ProtocolLib]
commands:
  debug:
    description: Shows debug info
    usage: /debug
    default: op
  startgame:
    description: Starts the game
    usage: /startgame
    default: op
  endgame:
    description: Forces the game to end
    usage: /endgame
    default: op
  loadmap:
    description: Loads a map from the map pool
    usage: /loadmap
    default: op
  votestart:
    description: Vote to start the game
    usage: /votestart
  votemap:
    description: Vote for a map
    usage: /votemap
  team:
    description: Change your team
    usage: /team <red/blue/spectator>
  forceteam:
    description: Forces a player to join a team
    usage: /forceteam <player> <red/blue/spectator>
    default: op
  shuffleteams:
    description: Shuffles the teams
    usage: /shuffleteams
    default: op
  classes:
    description: Shows all CTF classes
    usage: /classes
  info:
    description: Shows info about a class
    usage: /info <class>
  tank:
    description: Equips the Tank class
    usage: /tank
  soldier:
    description: Equips the Soldier class
    usage: /soldier
  medic:
    description: Equips the Medic class
    usage: /medic
  archer:
    description: Equips the Archer class
    usage: /archer
  ninja:
    description: Equips the Ninja class
    usage: /ninja
  pyro:
    description: Equips the Pyro class
    usage: /pyro
  assassin:
    description: Equips the Assassin class
    usage: /assassin
  dwarf:
    description: Equips the Dwarf class
    usage: /dwarf
  chemist:
    description: Equips the Chemist class
    usage: /chemist
  md:
    description: Call for a medic
    usage: /md
  d:
    description: Tell your team to defend
    usage: /d
  c:
    description: Tell your team to be careful
    usage: /c
  b:
    description: Ask your Chemist for buffs
    usage: /b

