name: "ParallelCTF"
version: "1.0.0"
main: parallelmc.ctf.ParallelCTF
api-version: 1.18
author: EBro912
description: A Capture the Flag plugin for Parallel events
commands:
  debug:
    description: Shows debug info
    usage: /debug
    default: op
  startgame:
    description: Starts the game
    usage: /startgame
    default: op
  endgame:
    description: Forces the game to end
    usage: /endgame
    default: op
  team:
    description: Change your team
    usage: /team <red/blue>
  forceteam:
    description: Forces a player to join a team
    usage: /forceteam <player> <red/blue>
    default: op
  classes:
    description: Shows all CTF classes
    usage: /classes
  tank:
    description: Equips the Tank class
    usage: /tank
  soldier:
    description: Equips the Soldier class
    usage: /soldier
  medic:
    description: Equips the Medic class
    usage: /medic
  archer:
    description: Equips the Archer class
    usage: /archer
  ninja:
    description: Equips the Ninja class
    usage: /ninja
  pyro:
    description: Equips the Pyro class
    usage: /pyro
  assassin:
    description: Equips the Assassin class
    usage: /assassin
  dwarf:
    description: Equips the Dwarf class
    usage: /dwarf

